redis repo changes

diff --git a/.github/workflows/docker-build-push.yml b/.github/workflows/docker-build-push.yml
--- a/.github/workflows/docker-build-push.yml
+++ b/.github/workflows/docker-build-push.yml
@@ -5,43 +5,43 @@ on:
     branches:
       - main
     tags:
-      - '[0-9]+.[0-9]+.[0-9]+'
+      - "[0-9]+.[0-9]+.[0-9]+"
 
 jobs:
   build-and-push:
     runs-on: ubuntu-latest
 
     steps:
-    - name: Checkout repository
-      uses: actions/checkout@v3
+      - name: Checkout repository
+        uses: actions/checkout@v3
 
-    - name: Validate tag format
-      id: validate
-      run: |
-        if [[ ! "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
-          echo "Error: Tag must be in format X.Y.Z"
-          exit 1
-        fi
-        echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
+      - name: Validate tag format
+        id: validate
+        run: |
+          if [[ ! "${{ github.ref_name }}" =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
+            echo "Error: Tag must be in format X.Y.Z"
+            exit 1
+          fi
+          echo "tag=${{ github.ref_name }}" >> $GITHUB_ENV
 
-    - name: Log in to Docker Hub
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Log in to Docker Hub
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-    - name: Check if image with tag already exists
-      run: |
-        if docker manifest inspect sharetube/server:${{ env.tag }} &> /dev/null; then
-          echo "Image with tag ${{ env.tag }} already exists, skipping push"
-          exit 0
-        fi
+      - name: Check if image with tag already exists
+        run: |
+          if docker manifest inspect sharetube/server:${{ env.tag }} &> /dev/null; then
+            echo "Image with tag ${{ env.tag }} already exists, skipping push"
+            exit 0
+          fi
 
-    - name: Build Docker Image
-      run: |
-        docker build -t sharetube/server:${{ env.tag }} -t sharetube/server:latest .
+      - name: Build Docker Image
+        run: |
+          docker build -t sharetube/server:${{ env.tag }} -t sharetube/server:latest .
 
-    - name: Push Docker Image
-      run: |
-        docker push sharetube/server:${{ env.tag }}
-        docker push sharetube/server:latest
+      - name: Push Docker Image
+        run: |
+          docker push sharetube/server:${{ env.tag }}
+          docker push sharetube/server:latest
